### ISSUE TITLE
Errors during compilation

### ISSUE THREAD

**Issue by alexandershalin** [tsoliman/Retroflag-GPi-case#1]
I've got some errors when I try to compile:

> pi@retropie:~/Retroflag-GPi-case-master $ sudo ./compile-dts.sh
> dpi24-gpi.dtbo: Warning (unit_address_vs_reg): Node /fragment@0 has a unit name, but no reg property
> dpi24-gpi.dtbo: Warning (unit_address_vs_reg): Node /fragment@1 has a unit name, but no reg property
> pwm-audio-pi-zero-gpi.dtbo: Warning (unit_address_vs_reg): Node /fragment@0 has a unit name, but no reg property

Compiled files are created thought.

**Comment by SinisterSpatula** [comment]
those are just warnings, I think it's okay?

**Comment by tsoliman** [comment]
Fixed in c08a31d3e06e6f3a36aa9d70dc2f697516ee7c2a
